ilanguage: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
      sudo: required
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      sudo: required

git:
  submodules: false

before_install:
  - echo "CWD=$cwd"
  - export SCRIPTS=$cwd/travis
  - export BUILD_DIR=$cwd/build_skyline
  - export SV_TOP_DIR=$cwd
  - $SCRIPTS/travis_get_cmake_latest.sh

script: $SCRIPTS/travis_build.sh
