# GitHub build workflow configuration file.
# 
# This files defines the GitHub build actions which perform the following steps:
# 
#   - Building svOneDSolver on all supported platforms
#   - Creating installers for all supported platforms
#   - Uploading the generated installers as artifacts
#   - Uploading the generated installers as release assets (only for releases)

name: Build
on: [push, pull_request]
jobs:
  build-macos-catalina:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export TERM=xterm-256color
          export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
          mkdir Build
          cd Build
          cmake .. -DBUILD_SV_INSTALLER=ON
          make -j3
      - name: Create installer
        shell: bash
        run: |
          cd Build
          cpack
          cp oneD*.pkg ../svOneDSolver-macOS-Catalina.pkg
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS Catalina Installer
          path: svOneDSolver-macOS-Catalina.pkg
          if-no-files-found: error
      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: svOneDSolver-macOS-Catalina.pkg
          asset_name: svOneDSolver-${{github.ref_name}}-macOS-Catalina.pkg
          tag: ${{ github.ref }}

  build-ubuntu-20:
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Install dependencies
         shell: bash
         run: sudo apt-get install gcc-8 g++-8
       - name: Build
         shell: bash
         run: |
           export CC=/usr/bin/gcc-8
           export CXX=/usr/bin/g++-8
           mkdir Build
           cd Build
           cmake .. -DBUILD_SV_INSTALLER=ON
           make -j2
       - name: Create installer
         shell: bash
         run: |
           cd Build
           cpack
           cp oneD*.deb ../svOneDSolver-Ubuntu-20.deb
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: Ubuntu 20 Installer
           path: svOneDSolver-Ubuntu-20.deb
           if-no-files-found: error
       - name: Upload release asset
         if: startsWith(github.ref, 'refs/tags/')
         uses: svenstaro/upload-release-action@v2
         with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: svOneDSolver-Ubuntu-20.deb
           asset_name: svOneDSolver-${{github.ref_name}}-Ubuntu-20.deb
           tag: ${{ github.ref }}

